### ISSUE TITLE
Could you provide the dataset? 

### ISSUE THREAD

**Issue by GarrettLee** [Lichuanro/smoke-detection-transfer-learning#1]
Hi, 

The demo looks nice. But it seems that there is no dataset or link to dataset in the repo, so I failed running the scripts. Could you please provide it?

Thanks.

Li

**Comment by Lichuanro** [comment]
I use the dataset from the paper "High-order local ternary patterns with locality preserving projection for smoke detection and image classification" and the data is on **http://staff.ustc.edu.cn/~yfn/vsd.html**
And I also published it on **Floydhub**, you can goto **https://www.floydhub.com/licor/datasets/smoke**

**Comment by Lichuanro** [comment]
I provided the dataset links in the comment, sorry for the delaying.

2018-04-26 22:43 GMT+08:00 GarrettLee <notifications@github.com>:

**Comment by GarrettLee** [comment]
Yeah, I had found that so I closed the issue. But thank you so much
